### ISSUE TITLE
Is there a mistake in patchwork.hpp????

### ISSUE THREAD

**Issue by robot-wljywp** [LimHyungTae/patchwork#14]
Line 439
`if (ground_z_elevation > elevation_thr_[ring_idx + 2 * k]) {`

is index 'ring_idx + 2*k' wrong ?
the size of elevation_thr_ is 4. So, ' ring_idx + 2*k' may be large than 4.
Can you explain it?

**Comment by LimHyungTae** [comment]
Hello there, sorry for the late reply due to my paperwork!

But it is previously checked in 
`if (concentric_idx < num_rings_of_interest_) {` condition.
Please print `ring_idx + 2 * k` out :)
