### ISSUE TITLE
How to show pointcloud frame by frame?

### ISSUE THREAD

**Issue by mc171819** [LimHyungTae/patchwork#16]
Hi, it's a wonderful work! I'm a new user of ROS and I wonder how can I show the result of patchwork frame by frame, since your work show the result in a video-like style.

**Comment by LimHyungTae** [comment]
Hello @mc171819 ! Sorry for late reply due to the preparation of my graduation :(

Plase use below snippet!
```cpp
if (stop_for_each_frame) {
            cout<< "[Debug]: STOP!" <<endl;
            cin.ignore();
        }
```

Then, the frame would be stopped before you press any keys.
