### ISSUE TITLE
The different between code and paper

### ISSUE THREAD

**Issue by morte2025** [LimHyungTae/patchwork#17]
Thank you for your excellent work. In your paper, If the  probability of Ground Likelihood Estimation is larger than 0.5,  than ˆGn belongs to the actual ground. However,  I noticed you don't do this step,  Besides, the calculation of equation （10）and （11）didn't happen. I want to know whether it's just some kind of simplification.

**Comment by LimHyungTae** [comment]
I confess that the equations are quite redundant haha... But the equation exactly says the same things.

For more details, please refer to wiki:
https://github.com/LimHyungTae/patchwork/wiki/3.-Methodology-of-Patchwork

**Comment by LimHyungTae** [comment]
P.S. (-) symbol in (10) is wrong in https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9466396.

It is modified in arxiv version as follows:

![image](https://user-images.githubusercontent.com/35317311/178731401-d274f8f2-9654-4fc2-b923-c8e1b29ab73f.png)

It was my terrible mistake...I'll try my best to submit correction file ASAP.
