### ISSUE TITLE
patchwork.hpp:373

### ISSUE THREAD

**Issue by YixFeng** [LimHyungTae/patchwork#18]
`include/patchwork/patchwork.hpp:373: double PatchWork<PointT>::consensus_set_based_height_estimation(const RowVectorXd&, const RowVectorXd&, const RowVectorXd&) [with PointT = pcl::PointXYZ; Eigen::RowVectorXd = Eigen::Matrix<double, 1, -1>]: Assertion `!only_one_element' failed.`

Hi, when I tried to run my own data, some troubles occurred in this line.
I find some comments behind this line, i.e. "TODO: admit a trivial solution".
Is there any bugs when you debuged it?

**Comment by LimHyungTae** [comment]
could you give me your data or pcd files via e-mail or something? Thank you in advance
