### ISSUE TITLE
adaption for VLP16

### ISSUE THREAD

**Issue by bill4u** [LimHyungTae/patchwork#2]
Hello, thanks for your great work. Is there some examples or advices in parameters setting for the VLP16 data?

**Comment by LimHyungTae** [comment]
Hello,

To achieve ground estimation by using VLP-16, then I think setting CZM should be revised.

And note that for each bin, at least two scan lines are included. 

Otherwise, it is not guaranteed that the eigenvector corresponding to the smallest eigenvalue represents the normal vector.
