### ISSUE TITLE
Explanation needed of consensus_set_based_height_estimation() function

### ISSUE THREAD

**Issue by anaskhan496** [LimHyungTae/patchwork#21]
Hello @LimHyungTae,
Thank you for making this great work open-source. I have been going through the patchwork.hpp file and am having trouble understanding the consensus_set_based_height_estimation function. Could you explain what the function is doing when you pass the values, ranges, and weights? What is the physical significance of the linearities and planarities vector and their relation to the ranges, and weights? 

![Screenshot from 2022-10-11 15-33-46](https://user-images.githubusercontent.com/59138444/195182920-dd5b3a16-75f1-4981-889b-e553fc8529f3.png)

![Screenshot from 2022-10-11 15-34-41](https://user-images.githubusercontent.com/59138444/195182937-8c64d624-8c51-467b-9351-25d9c407daf6.png)

**Comment by LimHyungTae** [comment]
Hey, thank you for your interest. It's for estimating the actual sensor height from the ground. And we weights the planes which has large planarities when estimating `h`

**Comment by anaskhan496** [comment]
Thanks for the quick response. I see that the function estimates the height of the sensor. Can you provide more information on how you came up with the formulas for linearity, planarity, ranges, and weights. Knowing the significance of the formulas will be beneficial in understanding the height estimation function.

**Comment by LimHyungTae** [comment]
Hey, sorry for the rate reply. This module is for our T-RO paper, which is on revision. The original information can be found in TEASER++.

**Comment by LimHyungTae** [comment]
Component-wise translation estimation part in https://github.com/MIT-SPARK/TEASER-plusplus !
