### ISSUE TITLE
Under And over segmentation Ouster 128

### ISSUE THREAD

**Issue by faisalst** [LimHyungTae/patchwork#22]
Hello LIm,
I was wondering if you could help me with the issue I'm having with my data. It's over and under segmenting. I tried adjusting the parameters but no luck far. Thanks!

**Comment by LimHyungTae** [comment]
Sorry for too late reply :( since I was under defense and very busy days. By any change, if you provide pcd files, I'll test it! Thanks in advance

**Comment by LimHyungTae** [comment]
There's no response, so this issue is closed
