### ISSUE TITLE
Magic numbers in code

### ISSUE THREAD

**Issue by james-yoo** [LimHyungTae/patchwork#23]
Hi @LimHyungTae, 
Thanks for releasing the great work! I found that there are magic numbers in the code that can be effected the final extraction result as follow.
1) Could you please explain linearity?
https://github.com/LimHyungTae/patchwork/blob/93b493cb57d205dc3564229fd3f9d35977f39ecd/include/patchwork/patchwork.hpp#L460
2) Should I use a value larger than the sensor's mounting height?
https://github.com/LimHyungTae/patchwork/blob/93b493cb57d205dc3564229fd3f9d35977f39ecd/include/patchwork/patchwork.hpp#L525
3) What is the meaning of the size of the point cloud?
https://github.com/LimHyungTae/patchwork/blob/93b493cb57d205dc3564229fd3f9d35977f39ecd/include/patchwork/patchwork.hpp#L283

**Comment by james-yoo** [comment]
ping @LimHyungTae,

**Comment by LimHyungTae** [comment]
True:
1. If linearity is too large, it means that ground points are likely to be a single channel, which should be avoided when getting average height via ATAT
2. To reject some undesirable noisy points
3. Just for reserve mode to prevent inefficient memory copy & paste on the 0-th operation

**Comment by james-yoo** [comment]
Great. Thanks!
