### ISSUE TITLE
prabally code error

### ISSUE THREAD

**Issue by morte2025** [LimHyungTae/patchwork#29]
It seems that line 186 "concentric_idx_tmp++; " should be put behind line 187.

**Comment by LimHyungTae** [comment]
Could you please why? I don't think so, because it's the index for rings from the central to far part (maybe I have to change it to more appropriate names)

**Comment by morte2025** [comment]
Because the value of "num_rings_each_zone" may be bigger than 1. Therefore the ring index may be different from the zone index.  For example,  in variables flatness_thr_[concentric_idx],  concentric_idx may be greater than 3.  I think concentric_idx should be the zone index, not the ring index.

**Comment by LimHyungTae** [comment]
Well, the flatness term is only applied to the closest rings, not the zone. Because we cannot discern between flat but steep slope and just non-ground, flat objects when the distance from the origin becomes large. That's why elevation and flatness are applied to the closest rings.

**Comment by morte2025** [comment]
Thanks.
