### ISSUE TITLE
the performance of the proposed components

### ISSUE THREAD

**Issue by shouldnotfail** [LimHyungTae/patchwork#8]
Thanks for sharing the awsome works pathwork and erasor!  And I wonder can CZM & GLE lead to performance gain when using erasor?

**Comment by LimHyungTae** [comment]
Sure I guess, it would reject some false positive patches!

**Comment by shouldnotfail** [comment]
Aftering reading the code carefully, I found that the ground likelihood is represented by some discrete states, which is not same as the description in paper. The reason is the difficulty of parameters tuning?

**Comment by LimHyungTae** [comment]
Above all things, thank you for interest 😍! In fact, the GLE is the equation seems like fancy but eventually it means binary decision haha....

**Comment by LimHyungTae** [comment]
I'll share my slides in IROS'21 to help you understand better, which below pipeline is identical with the GLE equation step-by-step!
![image](https://user-images.githubusercontent.com/35317311/147621493-9fa14d86-a11e-4e18-b7a5-76bed4ccfe91.png)
![image](https://user-images.githubusercontent.com/35317311/147621513-6ca4a502-05b9-4d7a-b6e2-d8349bee7e6a.png)
![image](https://user-images.githubusercontent.com/35317311/147621521-392bc8c6-e38d-49bb-9cd7-344c10a373c5.png)

**Comment by shouldnotfail** [comment]
got the same feeling! the invese sensor model in lidar based freespace detection always turn to be binary classifier too. Thanks again for the reply!

**Comment by LimHyungTae** [comment]
Cheers~ Hope your search improves my method!
